$axure.loadCurrentPage({
  "url":"yonghushenhe.html",
  "generationDate":new Date(1417576555334.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/zhuce/bg.jpg",
    "width":576,
    "height":360},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"892d69412f504405afec44daad01f1c6",
    "type":"Axure:Page",
    "name":"yonghushenhe",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"01d49bec0b8847ea9ae80fdc54c482cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":41},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29fa0b0b8b5544b18db41e954814085f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":41},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"5268519944664e468f178bfb0062318c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":960,
              "y":46},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4469b171257b49f4b65a910f0465c4dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":960,
                  "y":46},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd7e8eef6a7d494ab0388197c45192c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1024,
              "y":46},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8171cb9bc5e14e769acf74cb3124b987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1024,
                  "y":46},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"081cb914e7e74807a64a2e672dfd175c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1087,
              "y":46},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9bd64d2cecb44cd86f220efa9ecb674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1087,
                  "y":46},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95006f87f12347e3a0d3a1520161a5e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1133,
              "y":46},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26821251b70644aa9dbd7f1192068754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1133,
                  "y":46},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t_ziliao/u8.jpg"}},
{
          "id":"3799d130e2b04fb3872373d453c366d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1011,
              "y":80},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f844135844c441a28c1abc25abe13809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1011,
                  "y":80},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a70bcf49548245bca455b00f21f3048e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1074,
              "y":80},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d97140029e3840968aa5b8876e091383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1074,
                  "y":80},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faa58aaceac24487b14c958620d083c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.8",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":156,
              "y":180},
            "size":{
              "width":1024,
              "height":520},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97e2d2b62154401a599075495953817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":156,
                  "y":180},
                "size":{
                  "width":1024,
                  "height":520},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u2.png"}},
{
          "id":"6ce36b8d87eb45c096d2be6d7f3fe220",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":240},
            "size":{
              "width":119,
              "height":460},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00762654d26848569146ec78204eabe5",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":119,
                  "height":460}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c86ccb3f3854fea8c1062a3e2b2fd48",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "size":{
                      "width":119,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d325d986ad124b929d96dbb27d6e4de2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "size":{
                          "width":119,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/t_ziliao/u18.png"}},
{
                  "id":"20636a3c2a2c4a6eabd9f2f68186dae9",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":119,
                      "height":45},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45d3237112e946f3bc1979cce0985333",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":119,
                          "height":45},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 重新加载",
                              "target":{
                                "targetType":"reloadPage",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u20.png"}},
{
                  "id":"eecfa320438e4dd0bdf24c280e44abcf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":119,
                      "height":39},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9786b6e6121b48f2a8b219a1725f3627",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":119,
                          "height":39},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 tiezishenhe",
                              "target":{
                                "targetType":"page",
                                "url":"tiezishenhe.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u24.png"}},
{
                  "id":"81bc011c4f2c4e76860fc9cedac0bc25",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":105},
                    "size":{
                      "width":119,
                      "height":45},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f6a6568de274235bf2978a49e0f5e97",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":105},
                        "size":{
                          "width":119,
                          "height":45},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 jiaoshishenhe",
                              "target":{
                                "targetType":"page",
                                "url":"jiaoshishenhe.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u20.png"}},
{
                  "id":"dc19e18a78884ad1b65217ce0de91821",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":189},
                    "size":{
                      "width":119,
                      "height":271},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ba4b1f78f654641a9fd03b7ae78672c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":189},
                        "size":{
                          "width":119,
                          "height":271},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/t_ziliao/u26.png"}}]}]},
{
          "id":"2b337077cd6a470bb4d52d270875d09f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":190},
            "size":{
              "width":1024,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e723ffcf51394f25ac39f30b96bcd80a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1024,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d4e3e2e0f96453ca35ae006e26ff29b",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f99892c307e94e4f92940e70e02810da",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"25b5d68ead2b4455aa8db886ada5e129",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55f2739ed86c4717ab57ed675af79226",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"a44ddfef55244619920e1986a3c9a2df",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28573eae197440209bd82ad058d183c5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"ba988bb7d1614003913945b8bdf8fcd2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":375,
                      "y":0},
                    "size":{
                      "width":649,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d2f1596d28e48d99620edd2a378667e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":375,
                          "y":0},
                        "size":{
                          "width":649,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u79.png"}}]}]},
{
          "id":"ee2c52374d7445be8618fb900db42167",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":156,
              "y":215},
            "size":{
              "width":1024,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_ziliao/u50_line.png"}},
{
          "id":"e486bc37e9334c4fa708fb704d2d3ba2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":156,
              "y":184},
            "size":{
              "width":1024,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_ziliao/u50_line.png"}},
{
          "id":"223cfeab2a9d488fa2aa49956265f758",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":154,
              "y":240},
            "size":{
              "width":10,
              "height":459}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_mima/u41_line.png"}},
{
          "id":"e1e3229e306c44a489006a4f46709295",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":160,
              "y":235},
            "size":{
              "width":121,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u41_line.png"}},
{
          "id":"5a198c2d282c4ea9947969875bd1a4a3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":160,
              "y":694},
            "size":{
              "width":120,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u42_line.png"}},
{
          "id":"1f1acc93ce0641c58da10923f30170db",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":294},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"049a0c4465954583a9a41166d5424bfb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":340},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"6bba3988020f4ab88ed7f4b09d034753",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":385},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"5038bd1158aa49a98c30d4824dc137c2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":423},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"22b8ff9e8c39452095deb0579853bfeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFE8F0F7},
            "location":{
              "x":279,
              "y":240},
            "size":{
              "width":901,
              "height":30},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a55f8d1277a4a48a1441d987cc302c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE8F0F7},
                "location":{
                  "x":279,
                  "y":240},
                "size":{
                  "width":901,
                  "height":30},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t_ziliao/u47.png"}},
{
          "id":"4c947b294242464d8978fb09655dd6ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":279,
              "y":264},
            "size":{
              "width":901,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u49_line.png"}},
{
          "id":"cad92f3857b342ad9b4e5d5f5bf81f03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":279,
              "y":235},
            "size":{
              "width":901,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u49_line.png"}},
{
          "id":"4553f0c851354fa2a26ede0c892c356e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":190},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bdb7d6457f34c6fa1809a7ec003936e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":170,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u96.png"}},
{
          "id":"1fa7db1054b44c2eb100aee00065eabe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":274,
              "y":240},
            "size":{
              "width":10,
              "height":459}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_mima/u41_line.png"}},
{
          "id":"b912de2f2512451a98e28b055ee2ad3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":274,
              "y":194},
            "size":{
              "width":16,
              "height":21},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64163bbc5ad4da48a2b7397053146ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":274,
                  "y":194},
                "size":{
                  "width":16,
                  "height":21},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u98.png"}},
{
          "id":"7941c50acdad4be58021b9ed6b137ce1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":394,
              "y":194},
            "size":{
              "width":16,
              "height":21},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90afb463937f492cba0347a1a39e8a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":394,
                  "y":194},
                "size":{
                  "width":16,
                  "height":21},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u98.png"}},
{
          "id":"5b4249ea471f4605b3e45c6b01b02700",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":314,
              "y":338},
            "size":{
              "width":660,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b39dd9ab3314b81a010fff2088fa7e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":165,
                  "height":88}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"529213a433294275a88661311a5926ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":165,
                      "height":88}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u59.png"}},
{
              "id":"6b1c5eb14286436dbb6dc6af1e54508f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":88},
                "size":{
                  "width":165,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eec87112775c4f85b6664538f3ce6143",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":165,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u67.png"}},
{
              "id":"47c6ea9796d449988a257470d91aaa01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":135},
                "size":{
                  "width":165,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73b82fd2899b4a7299209217296a49f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":135},
                    "size":{
                      "width":165,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u75.png"}},
{
              "id":"369d3201e1584a059c63d83f20058580",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":0},
                "size":{
                  "width":165,
                  "height":88}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3276601c1d364f69a76cbf75023b78cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":165,
                      "y":0},
                    "size":{
                      "width":165,
                      "height":88}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u59.png"}},
{
              "id":"449cb1e3c53642a699b55163cf9784b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":88},
                "size":{
                  "width":165,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64f66cb4e8e94118b7b9b8998633e53e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":165,
                      "y":88},
                    "size":{
                      "width":165,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u67.png"}},
{
              "id":"d7a942a768b24809b45a72c96a37bc10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":135},
                "size":{
                  "width":165,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a669deb95c3f4b6f849cf70d81a38ce4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":165,
                      "y":135},
                    "size":{
                      "width":165,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u75.png"}},
{
              "id":"346d0e99a7c04b5781956ec6c9266160",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":330,
                  "y":0},
                "size":{
                  "width":165,
                  "height":88}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2e87893337e4c0b8afcbce814b34197",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":330,
                      "y":0},
                    "size":{
                      "width":165,
                      "height":88}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u59.png"}},
{
              "id":"00f75472411c48f5b08a3ce55e99a0a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":330,
                  "y":88},
                "size":{
                  "width":165,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f6eded7708b42b1a44d177d96488e5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":330,
                      "y":88},
                    "size":{
                      "width":165,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u67.png"}},
{
              "id":"21842477626c475583761b8beadad3c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":330,
                  "y":135},
                "size":{
                  "width":165,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dc63d92b2f14e67beacb6e15b731783",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":330,
                      "y":135},
                    "size":{
                      "width":165,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u75.png"}},
{
              "id":"fd90f63d18144c43902d0da4fc59b8d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":495,
                  "y":0},
                "size":{
                  "width":165,
                  "height":88}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd38bf6a92fa45e58e06a4f99f11e3c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":495,
                      "y":0},
                    "size":{
                      "width":165,
                      "height":88}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u65.png"}},
{
              "id":"e3a7491055b74a66abd25cf57b605bcb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":495,
                  "y":88},
                "size":{
                  "width":165,
                  "height":47}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c70d23d47afc41a6985bc45b50ecbc99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":495,
                      "y":88},
                    "size":{
                      "width":165,
                      "height":47}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"setFunction",
                          "description":"设置 文字于 (表格单元) = &quot;审核通过&quot;",
                          "expr":{
                            "exprType":"block",
                            "subExprs":[{
                                "exprType":"fcall",
                                "functionName":"SetWidgetRichText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["c70d23d47afc41a6985bc45b50ecbc99"]},
{
                                    "exprType":"stringLiteral",
                                    "value":"审核通过",
                                    "stos":[]},
{
                                    "exprType":"booleanLiteral",
                                    "value":true}]}]}}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/yonghushenhe/u73.png"}},
{
              "id":"6c38726f1a1f4979b991fe4f47a6951a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":495,
                  "y":135},
                "size":{
                  "width":165,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abe3a89ca0df473d9500cba6615cba23",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":495,
                      "y":135},
                    "size":{
                      "width":165,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/yonghushenhe/u81.png"}}]},
{
          "id":"23829eb3fb4f4f4c828a8d5d8e15ee26",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2592F5},
            "location":{
              "x":160,
              "y":117},
            "size":{
              "width":881,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8adce7c5f0b943e79dfb37e53ab1c97b",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":881,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db96fd7bbb6144219261872f67910ee6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF0099FF},
{
                          "color":0xFF0099FF},
{
                          "color":0xFF00FFFF},
{
                          "color":0xFF00FFFF}]},
                    "textShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}},
                    "size":{
                      "width":881,
                      "height":43},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x75CCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ff0b116f48e44259e1520647d409827",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF0099FF},
{
                              "color":0xFF0099FF},
{
                              "color":0xFF00FFFF},
{
                              "color":0xFF00FFFF}]},
                        "textShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}},
                        "size":{
                          "width":881,
                          "height":43},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x75CCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/zhuce/u37.png"}}]}]},
{
          "id":"4360a5ef7cb7465aac8f07b4abb2b123",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":156,
              "y":117},
            "size":{
              "width":148,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0x5BFFFFFF},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":204,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b361953e735240b8a3f9aa711b93a8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":156,
                  "y":117},
                "size":{
                  "width":148,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x5BFFFFFF},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":204,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 luntan",
                      "target":{
                        "targetType":"page",
                        "url":"luntan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/zhuce/u39.png"}},
{
          "id":"7d1f3cd2ce4f46c68c990521b67ddffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":452,
              "y":117},
            "size":{
              "width":138,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370461762ef449a0a5ead42eb8baa226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":452,
                  "y":117},
                "size":{
                  "width":138,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u41.png"}},
{
          "id":"01354c8a03e14710a4df857049c54e16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":1037,
              "y":117},
            "size":{
              "width":146,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15de76d1cb314be298ca3b6f9b5c2ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":1037,
                  "y":117},
                "size":{
                  "width":146,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u43.png"}},
{
          "id":"4dab79309b8f491cb31ec0f6b4648bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":304,
              "y":117},
            "size":{
              "width":148,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":204,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8dd9f54b87d45aea3b3b1c2563eb23f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":304,
                  "y":117},
                "size":{
                  "width":148,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":204,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 luntan",
                      "target":{
                        "targetType":"page",
                        "url":"luntan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/zhuce/u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "01d49bec0b8847ea9ae80fdc54c482cf":{
      "scriptId":"u0"},
    "29fa0b0b8b5544b18db41e954814085f":{
      "scriptId":"u1"},
    "5268519944664e468f178bfb0062318c":{
      "scriptId":"u2"},
    "4469b171257b49f4b65a910f0465c4dd":{
      "scriptId":"u3"},
    "cd7e8eef6a7d494ab0388197c45192c2":{
      "scriptId":"u4"},
    "8171cb9bc5e14e769acf74cb3124b987":{
      "scriptId":"u5"},
    "081cb914e7e74807a64a2e672dfd175c":{
      "scriptId":"u6"},
    "f9bd64d2cecb44cd86f220efa9ecb674":{
      "scriptId":"u7"},
    "95006f87f12347e3a0d3a1520161a5e9":{
      "scriptId":"u8"},
    "26821251b70644aa9dbd7f1192068754":{
      "scriptId":"u9"},
    "3799d130e2b04fb3872373d453c366d4":{
      "scriptId":"u10"},
    "f844135844c441a28c1abc25abe13809":{
      "scriptId":"u11"},
    "a70bcf49548245bca455b00f21f3048e":{
      "scriptId":"u12"},
    "d97140029e3840968aa5b8876e091383":{
      "scriptId":"u13"},
    "faa58aaceac24487b14c958620d083c0":{
      "scriptId":"u14"},
    "c97e2d2b62154401a599075495953817":{
      "scriptId":"u15"},
    "6ce36b8d87eb45c096d2be6d7f3fe220":{
      "scriptId":"u16"},
    "00762654d26848569146ec78204eabe5":{
      "scriptId":"u17"},
    "5c86ccb3f3854fea8c1062a3e2b2fd48":{
      "scriptId":"u18"},
    "d325d986ad124b929d96dbb27d6e4de2":{
      "scriptId":"u19"},
    "20636a3c2a2c4a6eabd9f2f68186dae9":{
      "scriptId":"u20"},
    "45d3237112e946f3bc1979cce0985333":{
      "scriptId":"u21"},
    "81bc011c4f2c4e76860fc9cedac0bc25":{
      "scriptId":"u22"},
    "1f6a6568de274235bf2978a49e0f5e97":{
      "scriptId":"u23"},
    "eecfa320438e4dd0bdf24c280e44abcf":{
      "scriptId":"u24"},
    "9786b6e6121b48f2a8b219a1725f3627":{
      "scriptId":"u25"},
    "dc19e18a78884ad1b65217ce0de91821":{
      "scriptId":"u26"},
    "5ba4b1f78f654641a9fd03b7ae78672c":{
      "scriptId":"u27"},
    "2b337077cd6a470bb4d52d270875d09f":{
      "scriptId":"u28"},
    "e723ffcf51394f25ac39f30b96bcd80a":{
      "scriptId":"u29"},
    "9d4e3e2e0f96453ca35ae006e26ff29b":{
      "scriptId":"u30"},
    "f99892c307e94e4f92940e70e02810da":{
      "scriptId":"u31"},
    "25b5d68ead2b4455aa8db886ada5e129":{
      "scriptId":"u32"},
    "55f2739ed86c4717ab57ed675af79226":{
      "scriptId":"u33"},
    "a44ddfef55244619920e1986a3c9a2df":{
      "scriptId":"u34"},
    "28573eae197440209bd82ad058d183c5":{
      "scriptId":"u35"},
    "ba988bb7d1614003913945b8bdf8fcd2":{
      "scriptId":"u36"},
    "2d2f1596d28e48d99620edd2a378667e":{
      "scriptId":"u37"},
    "ee2c52374d7445be8618fb900db42167":{
      "scriptId":"u38"},
    "e486bc37e9334c4fa708fb704d2d3ba2":{
      "scriptId":"u39"},
    "223cfeab2a9d488fa2aa49956265f758":{
      "scriptId":"u40"},
    "e1e3229e306c44a489006a4f46709295":{
      "scriptId":"u41"},
    "5a198c2d282c4ea9947969875bd1a4a3":{
      "scriptId":"u42"},
    "1f1acc93ce0641c58da10923f30170db":{
      "scriptId":"u43"},
    "049a0c4465954583a9a41166d5424bfb":{
      "scriptId":"u44"},
    "6bba3988020f4ab88ed7f4b09d034753":{
      "scriptId":"u45"},
    "5038bd1158aa49a98c30d4824dc137c2":{
      "scriptId":"u46"},
    "22b8ff9e8c39452095deb0579853bfeb":{
      "scriptId":"u47"},
    "3a55f8d1277a4a48a1441d987cc302c5":{
      "scriptId":"u48"},
    "4c947b294242464d8978fb09655dd6ec":{
      "scriptId":"u49"},
    "cad92f3857b342ad9b4e5d5f5bf81f03":{
      "scriptId":"u50"},
    "4553f0c851354fa2a26ede0c892c356e":{
      "scriptId":"u51"},
    "4bdb7d6457f34c6fa1809a7ec003936e":{
      "scriptId":"u52"},
    "1fa7db1054b44c2eb100aee00065eabe":{
      "scriptId":"u53"},
    "b912de2f2512451a98e28b055ee2ad3a":{
      "scriptId":"u54"},
    "e64163bbc5ad4da48a2b7397053146ab":{
      "scriptId":"u55"},
    "7941c50acdad4be58021b9ed6b137ce1":{
      "scriptId":"u56"},
    "90afb463937f492cba0347a1a39e8a17":{
      "scriptId":"u57"},
    "5b4249ea471f4605b3e45c6b01b02700":{
      "scriptId":"u58"},
    "6b39dd9ab3314b81a010fff2088fa7e3":{
      "scriptId":"u59"},
    "529213a433294275a88661311a5926ae":{
      "scriptId":"u60"},
    "369d3201e1584a059c63d83f20058580":{
      "scriptId":"u61"},
    "3276601c1d364f69a76cbf75023b78cc":{
      "scriptId":"u62"},
    "346d0e99a7c04b5781956ec6c9266160":{
      "scriptId":"u63"},
    "c2e87893337e4c0b8afcbce814b34197":{
      "scriptId":"u64"},
    "fd90f63d18144c43902d0da4fc59b8d9":{
      "scriptId":"u65"},
    "dd38bf6a92fa45e58e06a4f99f11e3c5":{
      "scriptId":"u66"},
    "6b1c5eb14286436dbb6dc6af1e54508f":{
      "scriptId":"u67"},
    "eec87112775c4f85b6664538f3ce6143":{
      "scriptId":"u68"},
    "449cb1e3c53642a699b55163cf9784b7":{
      "scriptId":"u69"},
    "64f66cb4e8e94118b7b9b8998633e53e":{
      "scriptId":"u70"},
    "00f75472411c48f5b08a3ce55e99a0a7":{
      "scriptId":"u71"},
    "7f6eded7708b42b1a44d177d96488e5b":{
      "scriptId":"u72"},
    "e3a7491055b74a66abd25cf57b605bcb":{
      "scriptId":"u73"},
    "c70d23d47afc41a6985bc45b50ecbc99":{
      "scriptId":"u74"},
    "47c6ea9796d449988a257470d91aaa01":{
      "scriptId":"u75"},
    "73b82fd2899b4a7299209217296a49f0":{
      "scriptId":"u76"},
    "d7a942a768b24809b45a72c96a37bc10":{
      "scriptId":"u77"},
    "a669deb95c3f4b6f849cf70d81a38ce4":{
      "scriptId":"u78"},
    "21842477626c475583761b8beadad3c2":{
      "scriptId":"u79"},
    "5dc63d92b2f14e67beacb6e15b731783":{
      "scriptId":"u80"},
    "6c38726f1a1f4979b991fe4f47a6951a":{
      "scriptId":"u81"},
    "abe3a89ca0df473d9500cba6615cba23":{
      "scriptId":"u82"},
    "23829eb3fb4f4f4c828a8d5d8e15ee26":{
      "scriptId":"u83"},
    "8adce7c5f0b943e79dfb37e53ab1c97b":{
      "scriptId":"u84"},
    "db96fd7bbb6144219261872f67910ee6":{
      "scriptId":"u85"},
    "7ff0b116f48e44259e1520647d409827":{
      "scriptId":"u86"},
    "4360a5ef7cb7465aac8f07b4abb2b123":{
      "scriptId":"u87"},
    "b361953e735240b8a3f9aa711b93a8ff":{
      "scriptId":"u88"},
    "7d1f3cd2ce4f46c68c990521b67ddffd":{
      "scriptId":"u89"},
    "370461762ef449a0a5ead42eb8baa226":{
      "scriptId":"u90"},
    "01354c8a03e14710a4df857049c54e16":{
      "scriptId":"u91"},
    "15de76d1cb314be298ca3b6f9b5c2ec7":{
      "scriptId":"u92"},
    "4dab79309b8f491cb31ec0f6b4648bbb":{
      "scriptId":"u93"},
    "f8dd9f54b87d45aea3b3b1c2563eb23f":{
      "scriptId":"u94"}}});