$axure.loadCurrentPage({
  "url":"t_ziliao.html",
  "generationDate":new Date(1417576554684.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/zhuce/bg.jpg",
    "width":576,
    "height":360},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"ad774299fa394048b80ae31607839dc6",
    "type":"Axure:Page",
    "name":"t_ziliao",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"089bcaa91c2c4c4db94785f96148a6aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":41},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"840e5b7821a64673a1903c528c964829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":41},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"ff203d1feb7b4f6581ed3581606507cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":967,
              "y":46},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60cbbc3d77e54102826a60b5d40dabfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":967,
                  "y":46},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c3225fdb0654b87950c55bab06d9c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1024,
              "y":46},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0022725894d047f3a5486b8d6cba69e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1024,
                  "y":46},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 t_ziliao",
                      "target":{
                        "targetType":"page",
                        "url":"t_ziliao.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1902a9ee8a314535b13a2bebf20eaaf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1087,
              "y":46},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a18fb4b0a734c8eb3c5d064f4613cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1087,
                  "y":46},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6a0ca63b2c34563a79224f6b3ee83f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1133,
              "y":46},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c61f2f3a86f94273b91146fc63a85bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1133,
                  "y":46},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t_ziliao/u8.jpg"}},
{
          "id":"dba865f823d549209aea45748edfac8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1011,
              "y":80},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46ad709250464b81ab172784ac042899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1011,
                  "y":80},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b244d3f9a1143788ded5ea544089f10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1074,
              "y":80},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac4d28b61624b73a473323a76625c33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1074,
                  "y":80},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f69b880f34054b128f074277604952bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "opacity":"0.8",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":156,
              "y":180},
            "size":{
              "width":1024,
              "height":520},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab330e2099a43429d7251ff75b7f4ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":156,
                  "y":180},
                "size":{
                  "width":1024,
                  "height":520},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u2.png"}},
{
          "id":"45f1bceef88e41dfa96132a6b410e332",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":240},
            "size":{
              "width":119,
              "height":460},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3d997d3c4d24115b9870e9c3f050669",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":119,
                  "height":460}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4c07b29414c4a0aaf2360a5952c05f1",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Bold', 'Applied Font'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "size":{
                      "width":119,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fee36d94c428469aa92b79bfb2212911",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Bold', 'Applied Font'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "size":{
                          "width":119,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/t_ziliao/u18.png"}},
{
                  "id":"a7bcff7b374f44b9a53d35ef66766b0c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":119,
                      "height":45},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25525f8f6acd4c599e1fa1970451adef",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":119,
                          "height":45},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_ziliao",
                              "target":{
                                "targetType":"page",
                                "url":"t_ziliao.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u20.png"}},
{
                  "id":"9aa80ef0a5f54949bd94157eb89e4cb7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":119,
                      "height":39},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a4c4f2eded34fa3b4e21327285fac15",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":119,
                          "height":39},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_mima",
                              "target":{
                                "targetType":"page",
                                "url":"t_mima.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u24.png"}},
{
                  "id":"6670b3327e7a4fabbdcfd3e474738792",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":105},
                    "size":{
                      "width":119,
                      "height":45},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a4142ff0d854f499caef637f62d4cc1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":105},
                        "size":{
                          "width":119,
                          "height":45},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_touxiang",
                              "target":{
                                "targetType":"page",
                                "url":"t_touxiang.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/t_ziliao/u20.png"}},
{
                  "id":"45ef09aefffb470c82531c7d6b65e5d4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":0,
                      "y":189},
                    "size":{
                      "width":119,
                      "height":271},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bee6b8e6e64940e7b14e39402e467a8c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":0,
                          "y":189},
                        "size":{
                          "width":119,
                          "height":271},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/t_ziliao/u26.png"}}]}]},
{
          "id":"9de0e2af872c44ef9302ab918785194c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":190},
            "size":{
              "width":1024,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3691732fb6964a58babff32e001694e4",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1024,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9d59289fae74490ae0059cf4595006f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a3b742874f745548f9238247658bcec",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"15ea576438df4353b2b1bf0fe9117187",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4090f710af5b43828919b8d90d48ef77",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"af0f56ad6e2845db8b54a7226f23fa65",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3cb959ebfcf4021a98ea7f2ccd9f8de",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u73.png"}},
{
                  "id":"2ac9c72f3d274a12928ff7cdf06ba5bf",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE8F0F7},
                    "location":{
                      "x":375,
                      "y":0},
                    "size":{
                      "width":649,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"321586cbeac944b1829bee08c28879e5",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE8F0F7},
                        "location":{
                          "x":375,
                          "y":0},
                        "size":{
                          "width":649,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/s_mima/u79.png"}}]}]},
{
          "id":"04f090aa35c6472ebef90c66edde8797",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":156,
              "y":215},
            "size":{
              "width":1024,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_ziliao/u50_line.png"}},
{
          "id":"59d72e32f93a44c394bd5b12cf8233fa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":156,
              "y":184},
            "size":{
              "width":1024,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_ziliao/u50_line.png"}},
{
          "id":"fc161b56acc14f82b4e645d28f9504bd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":154,
              "y":240},
            "size":{
              "width":10,
              "height":459}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_mima/u41_line.png"}},
{
          "id":"2a5cc026e5a84cf0bc21568bcd69d4f7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":160,
              "y":235},
            "size":{
              "width":121,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u41_line.png"}},
{
          "id":"a96b5a89c9c8442db5300c63b0f57772",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":160,
              "y":694},
            "size":{
              "width":120,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u42_line.png"}},
{
          "id":"581bc098ab594974b6408daa55c53de8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":294},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"2c177ab08ed246578b789115246bc663",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":340},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"1932a05aa8ef490f9a5b5ba57219c785",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":385},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"03eb7db1fc684aec82021d070abf6d56",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":162,
              "y":423},
            "size":{
              "width":115,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u43_line.png"}},
{
          "id":"39547e37928f4512ab4898c0346b7234",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "fill":{
              "fillType":"solid",
              "color":0xFFE8F0F7},
            "location":{
              "x":279,
              "y":240},
            "size":{
              "width":901,
              "height":30},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32438966b434bad86986d0bbc2400b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE8F0F7},
                "location":{
                  "x":279,
                  "y":240},
                "size":{
                  "width":901,
                  "height":30},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t_ziliao/u47.png"}},
{
          "id":"59e221a0a679472ca893cfaf940cd44e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":279,
              "y":264},
            "size":{
              "width":901,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u49_line.png"}},
{
          "id":"be935554ea1a46bd8fad9c16af9acaba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":279,
              "y":235},
            "size":{
              "width":901,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/t_ziliao/u49_line.png"}},
{
          "id":"f826b351a0f043b1b72d95aa6f035f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":314},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80695ca6b33a41e496d925b38542fb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":314},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5df93d9fba9b45509c560b68bd5245a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":354},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1329a183fcde40d4b5f80a75cef61ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":354},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad5a33f2c819404296cff5d03b4e26d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":394},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"384cfbe0f58e4ba39654cd2e9bd5101c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":394},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2000a0a5cd674a09b3733b6ce1504f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":472,
              "y":434},
            "size":{
              "width":40,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce90777871554befbfd65ac1458dae0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":472,
                  "y":434},
                "size":{
                  "width":40,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bd7b4aee9dc4a24ada732d21386ae4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":474},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28a7f86a55c0492f86d95bf581871ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":474},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da402a01861f4dd08112f3eb280bb57c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":314},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"479b03913a954dd1b081aa211730dc4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":601,
                  "y":314},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4956579c3894ee4bc3d1e34d34362dd",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":349.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"eca54254a635407e9e39073d012c24cd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":391},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ad20f0756ecb4fff8330c8d080f02124",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":431},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4be4add1de854a669323e1e16f426f23",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":684,
              "y":431},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"152c79e36eb04dc99fd00ef6a16393ee",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":769,
              "y":431},
            "size":{
              "width":64,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"073bf8920153400fbdb67e0fd11edfe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":665,
              "y":434},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c044ce7018474d49a8f8db81047f841d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":665,
                  "y":434},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90cf422287414014aed562737c156414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":748,
              "y":434},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfdf8f07859e47edbe665ed1f0ab2cc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":748,
                  "y":434},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c0bda413357449c8cf086b4f75c59a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":833,
              "y":434},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f79011021a444fbed78d25a4cfaeaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":833,
                  "y":434},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c753db8bf0c43fcb20628bbbaed3203",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":600,
              "y":471},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"43f02d06104145af8c06c6243b8446b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":514},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd5102e38bbd4c2cbb5fac4a582fc1b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":514},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeaaa42af9344f2d881bbbaa81e3cf02",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":509.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9ce165ec5dd34af09bf54084c6adae74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":190},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3788169ef8429ebb6dba1c5f00efd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":170,
                  "y":190},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u96.png"}},
{
          "id":"fff4873e690c42069db3b3ebd379967f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":274,
              "y":240},
            "size":{
              "width":10,
              "height":459}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/s_mima/u41_line.png"}},
{
          "id":"3b9c33a70d124e0bad83553add3c9bde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":471,
              "y":554},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f68658f14b074b6abf693211d0566000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":471,
                  "y":554},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"499f75abba0448e38329b4a384b08b5f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":601,
              "y":549.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"76d90cbc591643f3b8671d902f7513a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":274,
              "y":194},
            "size":{
              "width":16,
              "height":21},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0856b2fd139f49bb852beedc77c40f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":274,
                  "y":194},
                "size":{
                  "width":16,
                  "height":21},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u98.png"}},
{
          "id":"87a7d30a15894cb4b6593cd08dde17a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":394,
              "y":194},
            "size":{
              "width":16,
              "height":21},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75ac4c177154fcbaefda196e406d58a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":394,
                  "y":194},
                "size":{
                  "width":16,
                  "height":21},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/s_ziliao/u98.png"}},
{
          "id":"17c780761e664bbca5e31a080532ceb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF00CCFF},
{
                  "color":0xFF00CCFF},
{
                  "color":0xFF0099CC},
{
                  "color":0xFF0099CC}]},
            "location":{
              "x":471,
              "y":620},
            "size":{
              "width":59,
              "height":30},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cee9db4e77c40a3bc19757ac9805fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF00CCFF},
{
                      "color":0xFF00CCFF},
{
                      "color":0xFF0099CC},
{
                      "color":0xFF0099CC}]},
                "location":{
                  "x":471,
                  "y":620},
                "size":{
                  "width":59,
                  "height":30},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/t_ziliao/u88.png"}},
{
          "id":"4363d7c6d84b4c6b827fa870fbe2dc79",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2592F5},
            "location":{
              "x":160,
              "y":117},
            "size":{
              "width":881,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b52c07ed6f04ffaac3b45a8381f56cb",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":881,
                  "height":43}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3a4566b60804eeb99f76958943fc96d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFF0099FF},
{
                          "color":0xFF0099FF},
{
                          "color":0xFF00FFFF},
{
                          "color":0xFF00FFFF}]},
                    "textShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}},
                    "size":{
                      "width":881,
                      "height":43},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x75CCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a93be6523ed4dacb6164ec462e78c07",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFF0099FF},
{
                              "color":0xFF0099FF},
{
                              "color":0xFF00FFFF},
{
                              "color":0xFF00FFFF}]},
                        "textShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}},
                        "size":{
                          "width":881,
                          "height":43},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x75CCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/zhuce/u37.png"}}]}]},
{
          "id":"6884f9eee7ed44b3ac71d98ab8ccebb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":156,
              "y":117},
            "size":{
              "width":148,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0x5BFFFFFF},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":204,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f892ba78b5da4371969b556e61123a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":156,
                  "y":117},
                "size":{
                  "width":148,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x5BFFFFFF},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":204,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 luntan",
                      "target":{
                        "targetType":"page",
                        "url":"luntan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/zhuce/u39.png"}},
{
          "id":"4b59d59c5e07451abfa2c5c71f5aa1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":452,
              "y":117},
            "size":{
              "width":138,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b892b4e8e5045e486c5b6ed625c3428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":452,
                  "y":117},
                "size":{
                  "width":138,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u41.png"}},
{
          "id":"3cd7cdc023e742a58468e7a6d89a6827",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":1037,
              "y":117},
            "size":{
              "width":146,
              "height":43},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0a31d3b1eba4f2283afab9bfdd885f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":1037,
                  "y":117},
                "size":{
                  "width":146,
                  "height":43},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/zhuce/u43.png"}},
{
          "id":"579748c5917344c8bb7f69a16cabb7b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF00FFFF},
{
                  "color":0xFF00FFFF}]},
            "location":{
              "x":304,
              "y":117},
            "size":{
              "width":148,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"5",
            "outerShadow":{
              "on":false,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":204,
                "b":153,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e144cb403f4a779b4efcae62d8373e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF00FFFF},
{
                      "color":0xFF00FFFF}]},
                "location":{
                  "x":304,
                  "y":117},
                "size":{
                  "width":148,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"5",
                "outerShadow":{
                  "on":false,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":204,
                    "b":153,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 luntan",
                      "target":{
                        "targetType":"page",
                        "url":"luntan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/zhuce/u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "089bcaa91c2c4c4db94785f96148a6aa":{
      "scriptId":"u0"},
    "840e5b7821a64673a1903c528c964829":{
      "scriptId":"u1"},
    "ff203d1feb7b4f6581ed3581606507cf":{
      "scriptId":"u2"},
    "60cbbc3d77e54102826a60b5d40dabfd":{
      "scriptId":"u3"},
    "2c3225fdb0654b87950c55bab06d9c43":{
      "scriptId":"u4"},
    "0022725894d047f3a5486b8d6cba69e2":{
      "scriptId":"u5"},
    "1902a9ee8a314535b13a2bebf20eaaf1":{
      "scriptId":"u6"},
    "6a18fb4b0a734c8eb3c5d064f4613cf5":{
      "scriptId":"u7"},
    "d6a0ca63b2c34563a79224f6b3ee83f6":{
      "scriptId":"u8"},
    "c61f2f3a86f94273b91146fc63a85bfd":{
      "scriptId":"u9"},
    "dba865f823d549209aea45748edfac8b":{
      "scriptId":"u10"},
    "46ad709250464b81ab172784ac042899":{
      "scriptId":"u11"},
    "4b244d3f9a1143788ded5ea544089f10":{
      "scriptId":"u12"},
    "2ac4d28b61624b73a473323a76625c33":{
      "scriptId":"u13"},
    "f69b880f34054b128f074277604952bf":{
      "scriptId":"u14"},
    "3ab330e2099a43429d7251ff75b7f4ac":{
      "scriptId":"u15"},
    "45f1bceef88e41dfa96132a6b410e332":{
      "scriptId":"u16"},
    "a3d997d3c4d24115b9870e9c3f050669":{
      "scriptId":"u17"},
    "f4c07b29414c4a0aaf2360a5952c05f1":{
      "scriptId":"u18"},
    "fee36d94c428469aa92b79bfb2212911":{
      "scriptId":"u19"},
    "a7bcff7b374f44b9a53d35ef66766b0c":{
      "scriptId":"u20"},
    "25525f8f6acd4c599e1fa1970451adef":{
      "scriptId":"u21"},
    "6670b3327e7a4fabbdcfd3e474738792":{
      "scriptId":"u22"},
    "4a4142ff0d854f499caef637f62d4cc1":{
      "scriptId":"u23"},
    "9aa80ef0a5f54949bd94157eb89e4cb7":{
      "scriptId":"u24"},
    "0a4c4f2eded34fa3b4e21327285fac15":{
      "scriptId":"u25"},
    "45ef09aefffb470c82531c7d6b65e5d4":{
      "scriptId":"u26"},
    "bee6b8e6e64940e7b14e39402e467a8c":{
      "scriptId":"u27"},
    "9de0e2af872c44ef9302ab918785194c":{
      "scriptId":"u28"},
    "3691732fb6964a58babff32e001694e4":{
      "scriptId":"u29"},
    "c9d59289fae74490ae0059cf4595006f":{
      "scriptId":"u30"},
    "4a3b742874f745548f9238247658bcec":{
      "scriptId":"u31"},
    "15ea576438df4353b2b1bf0fe9117187":{
      "scriptId":"u32"},
    "4090f710af5b43828919b8d90d48ef77":{
      "scriptId":"u33"},
    "af0f56ad6e2845db8b54a7226f23fa65":{
      "scriptId":"u34"},
    "e3cb959ebfcf4021a98ea7f2ccd9f8de":{
      "scriptId":"u35"},
    "2ac9c72f3d274a12928ff7cdf06ba5bf":{
      "scriptId":"u36"},
    "321586cbeac944b1829bee08c28879e5":{
      "scriptId":"u37"},
    "04f090aa35c6472ebef90c66edde8797":{
      "scriptId":"u38"},
    "59d72e32f93a44c394bd5b12cf8233fa":{
      "scriptId":"u39"},
    "fc161b56acc14f82b4e645d28f9504bd":{
      "scriptId":"u40"},
    "2a5cc026e5a84cf0bc21568bcd69d4f7":{
      "scriptId":"u41"},
    "a96b5a89c9c8442db5300c63b0f57772":{
      "scriptId":"u42"},
    "581bc098ab594974b6408daa55c53de8":{
      "scriptId":"u43"},
    "2c177ab08ed246578b789115246bc663":{
      "scriptId":"u44"},
    "1932a05aa8ef490f9a5b5ba57219c785":{
      "scriptId":"u45"},
    "03eb7db1fc684aec82021d070abf6d56":{
      "scriptId":"u46"},
    "39547e37928f4512ab4898c0346b7234":{
      "scriptId":"u47"},
    "b32438966b434bad86986d0bbc2400b7":{
      "scriptId":"u48"},
    "59e221a0a679472ca893cfaf940cd44e":{
      "scriptId":"u49"},
    "be935554ea1a46bd8fad9c16af9acaba":{
      "scriptId":"u50"},
    "f826b351a0f043b1b72d95aa6f035f36":{
      "scriptId":"u51"},
    "80695ca6b33a41e496d925b38542fb6a":{
      "scriptId":"u52"},
    "5df93d9fba9b45509c560b68bd5245a0":{
      "scriptId":"u53"},
    "1329a183fcde40d4b5f80a75cef61ec0":{
      "scriptId":"u54"},
    "ad5a33f2c819404296cff5d03b4e26d4":{
      "scriptId":"u55"},
    "384cfbe0f58e4ba39654cd2e9bd5101c":{
      "scriptId":"u56"},
    "2000a0a5cd674a09b3733b6ce1504f9f":{
      "scriptId":"u57"},
    "ce90777871554befbfd65ac1458dae0c":{
      "scriptId":"u58"},
    "5bd7b4aee9dc4a24ada732d21386ae4c":{
      "scriptId":"u59"},
    "28a7f86a55c0492f86d95bf581871ec7":{
      "scriptId":"u60"},
    "da402a01861f4dd08112f3eb280bb57c":{
      "scriptId":"u61"},
    "479b03913a954dd1b081aa211730dc4b":{
      "scriptId":"u62"},
    "e4956579c3894ee4bc3d1e34d34362dd":{
      "scriptId":"u63"},
    "eca54254a635407e9e39073d012c24cd":{
      "scriptId":"u64"},
    "ad20f0756ecb4fff8330c8d080f02124":{
      "scriptId":"u65"},
    "4be4add1de854a669323e1e16f426f23":{
      "scriptId":"u66"},
    "152c79e36eb04dc99fd00ef6a16393ee":{
      "scriptId":"u67"},
    "073bf8920153400fbdb67e0fd11edfe2":{
      "scriptId":"u68"},
    "c044ce7018474d49a8f8db81047f841d":{
      "scriptId":"u69"},
    "90cf422287414014aed562737c156414":{
      "scriptId":"u70"},
    "bfdf8f07859e47edbe665ed1f0ab2cc9":{
      "scriptId":"u71"},
    "6c0bda413357449c8cf086b4f75c59a4":{
      "scriptId":"u72"},
    "38f79011021a444fbed78d25a4cfaeaa":{
      "scriptId":"u73"},
    "7c753db8bf0c43fcb20628bbbaed3203":{
      "scriptId":"u74"},
    "43f02d06104145af8c06c6243b8446b6":{
      "scriptId":"u75"},
    "dd5102e38bbd4c2cbb5fac4a582fc1b2":{
      "scriptId":"u76"},
    "aeaaa42af9344f2d881bbbaa81e3cf02":{
      "scriptId":"u77"},
    "9ce165ec5dd34af09bf54084c6adae74":{
      "scriptId":"u78"},
    "2e3788169ef8429ebb6dba1c5f00efd7":{
      "scriptId":"u79"},
    "fff4873e690c42069db3b3ebd379967f":{
      "scriptId":"u80"},
    "3b9c33a70d124e0bad83553add3c9bde":{
      "scriptId":"u81"},
    "f68658f14b074b6abf693211d0566000":{
      "scriptId":"u82"},
    "499f75abba0448e38329b4a384b08b5f":{
      "scriptId":"u83"},
    "76d90cbc591643f3b8671d902f7513a8":{
      "scriptId":"u84"},
    "0856b2fd139f49bb852beedc77c40f09":{
      "scriptId":"u85"},
    "87a7d30a15894cb4b6593cd08dde17a9":{
      "scriptId":"u86"},
    "d75ac4c177154fcbaefda196e406d58a":{
      "scriptId":"u87"},
    "17c780761e664bbca5e31a080532ceb3":{
      "scriptId":"u88"},
    "2cee9db4e77c40a3bc19757ac9805fdd":{
      "scriptId":"u89"},
    "4363d7c6d84b4c6b827fa870fbe2dc79":{
      "scriptId":"u90"},
    "7b52c07ed6f04ffaac3b45a8381f56cb":{
      "scriptId":"u91"},
    "a3a4566b60804eeb99f76958943fc96d":{
      "scriptId":"u92"},
    "5a93be6523ed4dacb6164ec462e78c07":{
      "scriptId":"u93"},
    "6884f9eee7ed44b3ac71d98ab8ccebb1":{
      "scriptId":"u94"},
    "f892ba78b5da4371969b556e61123a96":{
      "scriptId":"u95"},
    "4b59d59c5e07451abfa2c5c71f5aa1fb":{
      "scriptId":"u96"},
    "0b892b4e8e5045e486c5b6ed625c3428":{
      "scriptId":"u97"},
    "3cd7cdc023e742a58468e7a6d89a6827":{
      "scriptId":"u98"},
    "f0a31d3b1eba4f2283afab9bfdd885f7":{
      "scriptId":"u99"},
    "579748c5917344c8bb7f69a16cabb7b5":{
      "scriptId":"u100"},
    "a7e144cb403f4a779b4efcae62d8373e":{
      "scriptId":"u101"}}});